ALTER TABLE pages ADD COLUMN IF NOT EXISTS sync_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE slots ADD COLUMN IF NOT EXISTS sync_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE components ADD COLUMN IF NOT EXISTS sync_version INTEGER NOT NULL DEFAULT 1;
